### PR TITLE
Fix area polygons (#114)

### PR DESCRIPTION
**Pull request by hannesj**
However, this does not completely fix the issue, as now some areas are now represented as both ways and areas. Most of then seem to be parking areas that are not explicitly tagged as areas. [example](https://www.openstreetmap.org/way/30001408)

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
Will merge it when we start working on the mapping/queries again - but it might take some time until we get there.

**Comment by lukasmartinelli** [comment]
> However, this does not completely fix the issue, as now some areas are now represented as both ways and areas. Most of then seem to be parking areas that are not explicitly tagged as areas. example

I think we can solve that by letting imposm3 importing all geometry types (and then it will hopefully figure out duplicates based on osm_id).

Do you @hannesj  have a plaza example that is not tagged as area so we can do testing?

**Comment by hannesj** [comment]
An example is http://www.openstreetmap.org/way/27597658 which is not explicitly tagged as an area.

**Comment by lukasmartinelli** [comment]
I am working on it on our `add_area_polygons` branch.
Sadly somehow GitHub doesn't get that it is your original code that has
been submitted at https://github.com/osm2vectortiles/osm2vectortiles/commit/eef98465fd7a9021c4254790c8757f5a54b2e726. Sorry for that.

I now import the road linestrings and road polygons separately as you suggested but then remove the duplicates in a view based on the osm_id. All other layers operate on that view.

```sql
CREATE OR REPLACE VIEW osm_unique_road AS (
    SELECT rp.osm_id, rp.geometry, rp.type, rp.service,
           rp.oneway, rp.is_bridge, rp.is_tunnel, rp.timestamp,
           rp.ref, rp.name, rp.name_en, rp.name_es,
           rp.name_fr, rp.name_de, rp.name_ru, rp.name_zh,
           rp.layer, rp.z_order
    FROM osm_road_polygon AS rp
    UNION ALL
    SELECT rl.osm_id, rl.geometry, rl.type, rl.service,
           rl.oneway, rl.is_bridge, rl.is_tunnel, rl.timestamp,
           rl.ref, rl.name, rl.name_en, rl.name_es,
           rl.name_fr, rl.name_de, rl.name_ru, rl.name_zh,
           rl.layer, rp.z_order
    FROM osm_road_linestring AS rl
    LEFT JOIN osm_road_polygon AS rp ON rp.osm_id = rl.osm_id
    WHERE rp.osm_id IS NULL
);
```

**Comment by hannesj** [comment]
@lukasmartinelli thanks. I added a second commit which removes the parking areas from the road linestrings. As per [OSM wiki](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking) it is used only for areas.

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli thanks. I added a second commit which removes the parking areas from the road linestrings. As per OSM wiki it is used only for areas.

We don't handle parking spaces right now, but they are quite a prominent feature that should be displayed somewhere. Mentioned in #166

**Comment by lukasmartinelli** [comment]
This plaza now works.
http://www.openstreetmap.org/way/26261827

Perhaps you can merge back the changes in `add_area_polygons` back to your remote branch and then I can merge the PR - because you initiated the change :+1: 

Or I just create a new PR - your call.

**Comment by hannesj** [comment]
Thanks, updated the original PR with your changes added.

**Comment by lukasmartinelli** [comment]
Great stuff @hannesj !! We still need to continue to work on it and I need to review and test the road polygon issue but this will happen in separate issues.

We also learned in this issue how to work with multiply geometry types and then
remove the duplicates.

**Comment by hannesj** [comment]
Also labels for road polygons need to be thought of

**Pull request merged**
