### PR TITLE
Split large Polygons

### LINKED ISSUE #314: Mapnik Timeouts
While on the PostGIS side everything is happy and shiny I now get a lot of Mapnik copy timeouts.
Namely Mapnik is on 400% CPU consuming GBs of data but producing nothing and is eventually failing - while no expensive queries go onto PostGIS.

One example of such a tile is this in the middle of nowhere.

geojson_io

Command to reproduce:

```bash
tilelive-copy --scheme 'pyramid' --minzoom 8 --maxzoom 14 --bounds='-22.5,79.6871841545,-21.09375,79.9359182463' --timeout=60000 --slow=60000 'tmsource:///tmp/project' 'mbtiles:///usr/src/app/ab1b9bc5f65b4bbbbb71994490e8516e06abdb14.mbtiles'
```

Investigated a bit by removing layers from tm2source to see what might be the problem.

- [x] removing water doesn't help
- [x] removing landuse doesn't help
- [x] removing waterway doesn't help
- [x] removing country_label, marine_label, state_label, place_label doesn't help
- [x] removing water_label doesn't help
- [x] removing aeroway, barrier_line, building, road doesn't help
- [x] removing landuse_overlay doesn't help
- [x] removing admin, poi_label, road_label, housenum_label, airport_label, rail_station_label doesn't help
- [x] removing waterway_label doesn't help

Okay at this point I just deleted everything except one layer the `rail_station_label`. At this point it works. So now I am adding the layers that might be the problem again as it seems it is not a single layer that is the problem.

Another crazy man's thought just switched the scheme from `pyramid` to `scanline`and then it actually starts faster (doesn't stall Mapnik at the beginning) and I see that all the z13 and z14 tiles require all about 30s of rendering time?!! until eventuall it times out as well.

So now the question is why do some tiles require 30s of rendering? Do they receive so much data that that Mapnik needs to much processing time (perhaps we forgot a where clause or something).

- [x] having just water using pyramid takes 1m and 10s
- [x] having just water using scanline takes 14s
- [x] having just water using pyramid takes 1m and 13 s

So scanline is better for a small bbox?

Continue with finding out what layer might be the problem by adding layers.

- [x] adding landuse and waterway to water with scanline takes takes 1m 14

So is either landuse or waterway the problem?

- [x] having just landuse using pyramid times out
- [x] having just water using pyramid takes 1m and 8s
- [x] having just waterway using pyramid takes 12s

So we now know that landuse is a good problem child for testing.

Let's do this differently again. Let's measure how much traffic flows from PostGIS into the worker when we just render this bbox.

It is a whooping **1.7 GB** and after that it times out (since I gave a copy timeout of 60s). That means something is really fishy.

Let's do this just for the layers.

- [x] having just waterway takes 10MB
- [x] having just water takes already 872MB
- [x] having just landuse takes even more 1.893GB  after which it times out
- [x] having just landuse with a timeout of 120s consumes 4.009 GB and also times out

So let's jump to some conclusions.

- Copy timeouts happen when Mapnik is waiting for the copy process from PostGIS to Mapnik and this takes longer than the specified timeout (per default 60s)
- The layer queries consume way too much input data aka they throw away nearly all data they receive

Actions.

- [x] Find out why landuse or water are consuming so much input data
- [x] Limit number of data transferred from PostGIS to Mapnik

### PR DESCRIPTION
**Pull request by lukasmartinelli**
Resolves #314.
Wait with merge until tested on south and north pole as well.

Since I cannot use `ST_Subdivide` we need to split the polygon using ST_Intersection and the same grid we are using for detecting dirty tiles to slice the polygons.

But this also gives use advantages. I am now creating the grid at z9 (at z10 it takes too long to create the split tables). Creating the split table can take 5-6hrs so I suggest we do it only once and not after every diff import (this also only affects around 4000 very large polygons in the world - things like natural parks and glaciers).

This helps to resolve the issues with the national park in Chile mentioned in #251.
Still need more tests to see how well it works for glaciers.

### CODE REVIEW

**Comment by stirringhalo** [comment]
Think these changes are ready to be integrated? I'm still running into timeout issues and for the purposes of performance, I'm thinking of subdividing those super-large polygons.

**Comment by lukasmartinelli** [comment]
> Think these changes are ready to be merged? I'm still running into timeout issues and for the purposes of performance, I'm thinking of subdividing those super-large polygons.

Yes will. Just have to decide whether to put it into `import-osm` or `import-sql` since it requires importing the `XYZ_Extent` SQL function first.

**Comment by stirringhalo** [comment]
Awesome, I grabbed the last changes. Looking great so far! Does this increase the DB size much?

**Comment by lukasmartinelli** [comment]
> Awesome, I grabbed the last changes. Looking great so far! Does this increase the DB size much?

On top of my head this only affects ~4k polygons.

**Comment by stirringhalo** [comment]
To confirm, the DB when imported is about 150 GB?

**Comment by lukasmartinelli** [comment]
> To confirm, the DB when imported is about 150 GB?

After initial import, now after two diff imports it grew to 176 GB on BTRFS disk and Postgres tells 172GB.
On what kind of hardware are you running the DB?

**Comment by stirringhalo** [comment]
> On what kind of hardware are you running the DB?

I installed a 250 GB SSD as I knew the HDD would be sluggish for DB. I've successfully done an import with the pre-split code where it was ~150 GB but I was getting a bit concerned about the total disk space size after this second import.

**Comment by stirringhalo** [comment]
Testing the changes now (I had accidentally merged your split-polygons master branch so the first imported failed). But you're missing landuse_split_polygon_table.sql from src/import-sql/!

**Comment by stirringhalo** [comment]
Question, does aa5049d simply ensure that the osm_landuse_split_polygon table is created prior to making the landuse and landuse_overlay views? I have all the changes except for  aa5049d and I'm still running into the issue of too large of geometries timing out. Going to dig into it, and see if I can either fix for this processing run or dump the large areas.

**Comment by lukasmartinelli** [comment]
Yes nothing more - won't help with the tineouts. Can you send the bbox,
tile coordinates where the timeouts occur? I am also still hunting for
other causes for the timeouts.

**Comment by stirringhalo** [comment]
I'll hold off sending any bboxes. I suspect it's because I didn't set the index flag in docker-compose.yml but manually indexed landuse on area so any complex road networks (a good chunk of the planet) were timing out

**Pull request merged**
