### PR TITLE
Testing ST_Subdivide polygons

### PR DESCRIPTION
**Pull request by stirringhalo**
This is a PR to allow testing of ST_Subdivide. It's forked from the current master, so should be mostly up to date.

It uses Postgres 9.5, postgis 2.2, and GEOS3.5 and is based on  https://github.com/gordlea/docker-postgis without SFCGAL. Tuning of Postgres has been temporarily disabled. It can still be stripped down further. No splitting of polygons is done based on area. The subdivide_polygons.sql file simply renames the previous tables, recreates with new st_subdivide geometry and then reindexes. No clustering is done at this point.

I've been testing on Greenland osm.pbfs from Geofabrik. So far, results are inconclusive but I probably have missed something (**edit from the future, the failed jobs were due to timeouts with zero-feature mbtiles!**). I think tuning on the number of vertices in ST_Subdivide is also needed. 

The current value is 1024 vertices. This results in a max(st_npoints(geometry)) of less 1024, (as compared to 185246) and increases the number of geometries from 2936 to 5385.

Prior to splitting, the osm_landuse_polygons was about 10MB, now it is 11MB (similar ~10% increases for gen0 and gen1). So the size penalty doesn't seem too bad

### CODE REVIEW

**Comment by stirringhalo** [comment]
My thoughts for other tables that may need to be subdivided if this works:

- [ ] osm_ocean_polygon
- [ ] osm_ocean_polygon_gen0 
- [ ] ne_10m_lakes
- [ ] ne_10m_ocean
- [ ] ne_110m_lakes
- [ ] ne_110m_ocean
- [ ] ne_50m_lakes
- [ ] ne_50m_ocean

**Comment by stirringhalo** [comment]
From #354, tiles in Greenland process in ~35ms instead of 5s!

**Comment by lukasmartinelli** [comment]
> From #354, tiles in Greenland process in ~35ms instead of 5s using ST_Subidivide!
>  🎉 1  
>  Hide all checks

Great work @stirringhalo.

We made you a core member of OSM2VectorTiles and added you to the organization (you can decline of course). I think you would be a great enhancement. Welcome and thanks for your engagement.

**Comment by stirringhalo** [comment]
> We made you a core member of OSM2VectorTiles and added you to the organization (you can decline of course). I think you would be a great addition. Welcome and thanks for your engagement.

Thank-you, I gratefully accept the offer!

I will do some further testing of ST_Subdivide on the full planet then I'll give the thumbs up on merging.

**Comment by stirringhalo** [comment]
ne_10m_lakes, ne_50m_lakes and ne_110m_lakes don't need to be split. Largest feature is 2604 points at 10m. Also the NE lake tables has a name column which I think is being used, so subdividing may break labels

**Comment by stirringhalo** [comment]
Further benchmark numbers comparing ST_Subdivided to non, using a BBOX region with -25.5,79.6871841545,-21.09375,79.9359182463", 0 -> 14. This is with "slow" on so I could track it's progress on individual tiles. Not quite a full oranges to oranges comparison as ST_Subdivide had Postgres 9.5 while non used 9.4. Timeouts were disabled.

Using 1024 vertices to split.

Numbers are rather higher as this is on slow HDD for now as my SSD is full of the planet DB.

ST_Subdivide: 2m 23s, averaged about 40/s at the final close. MBTiles is 576.5 kB. 5529 tiles.
Non: 13m 56s, averaged 7/s. MBTiles is 577.5 kB. 5529 tiles.

I'm surprised it's actually slightly smaller....

Next step is a full planet run from the import-sql stage onwards with timeouts disabled.

**Comment by lukasmartinelli** [comment]
> ne_10m_lakes, ne_50m_lakes and ne_110m_lakes don't need to be split. Largest feature is 2604 points at 10m. Also the NE lake tables has a name column which I think is being used, so subdividing may break labels

Good that NE is not the problem. I guess in osm_water_polygon there might be huge areas as well.

> Further benchmark numbers comparing ST_Subdivided to non, using a BBOX region with -25.5,79.6871841545,-21.09375,79.9359182463", 0 -> 14. This is with "slow" on so I could track it's progress on individual tiles. Not quite a full oranges to oranges comparison as ST_Subdivide had Postgres 9.5 while non used 9.4. Timeouts were disabled.

Seems like ST_Subdivide does have an impact. It is very good that we now have data to verify that.
Just give me a go with this branch and I will do a world reimport.

> Note to self, need to SetSRID otherwise layer-specific views fail
>  Hide all checks

So the SRID gets lost after subdividing?

**Comment by stirringhalo** [comment]
**Note to self, need to SetSRID otherwise layer-specific views fail**
 
Needs to be done for:

- [ ] osm_water_polygon
- [ ] osm_water_polygon_gen1
- [ ] osm_landuse_polygon_gen0
- [ ] osm_landuse_polygon_gen1
- [ ] osm_landuse_polygon
- [ ] osm_ocean_polygon
- [ ] osm_ocean_polygon_gen0
- [ ] ne_*m_lakes
- [ ] ne_*m_ocean

Any layer where two mismatched geometry columns are unioned, this needs to be fixed. Should be done with UpdateGeometrySRID so it doesn't need to be done on the fly in views.

**Comment by stirringhalo** [comment]
Please test now! I decided to redo my world import as it wasn't a clean slate after my previous split_polygon hacking. I can't confirm the SetSRID fixes beyond the fact they are syntactically correct. One or two of the SetSRIDs may be unnecessary as I was changing the geometry column types and manipulated SetSRID on my planet import.

I forced build on the necessary docker images (import-sql, export, export-remote, postgis) just to ease the first run.

I will be following soon with my own planet import once it completes again.

**Comment by stirringhalo** [comment]
I see that #171 references a different PGTune approach that supports 9.5. Will look into this at some point.

**Comment by lukasmartinelli** [comment]
> I see that #171 references a different PGTune approach that supports 9.5. Will look into this at some point.
>  Hide all checks

For me that is not necessary yet since I tune it for production anyways. We can merge it without. It was a nice to use though since most users wouldn't tune the DB otherwise.

I am now testing this branch on https://github.com/osm2vectortiles/osm2vectortiles/tree/new-import-v3.
Doing a new import and will try to render the recent changed tiles with this.

Have a bit more time at hands to look at all the awesome stuff you were up to @stirringhalo (fell a bit short sorry).

**Comment by stirringhalo** [comment]
> For me that is not necessary yet since I tune it for production anyways. We can merge it without. It was a nice to use though since most users wouldn't tune the DB otherwise.

Yep, and I've always been unsure if I'm making things better or worse by tuning! Max_connections and a few others will definitely be something to tune

> I am now testing this branch on https://github.com/osm2vectortiles/osm2vectortiles/tree/new-import-v3. Doing a new import and will try to render the recent changed tiles with this.

Sounds great, just saw the branch. I ran out of disk on my SSD as I forgot about the cache that was taking a fair bit of space already so I had to redo the import. Hence the no-diff option!

> Have a bit more time at hands to look at all the awesome stuff you were up to @stirringhalo (fell a bit short sorry).

No worries, I've enjoyed digging into timeout stuff over the weekend. I'm curious what other performance tweaks can be made to import-osm as very little of the time is spent actually writing OSM vs all the generalization/indexing tasks.

Once the ST_Subdivide gets merged, I will get it working more in parallel so it doesn't take so long on the create table, etc operations. But from my testing before I reimported, it wasn't taking too long, perhaps an hour or two. Much faster than split_polygon.

**Comment by ImreSamu** [comment]
my proposal for the new pgtune :  https://github.com/osm2vectortiles/pgtune
( it is clean and simple code - for me )
If no other better solution - I will try to customize ..

**Comment by lukasmartinelli** [comment]
> my proposal for the new pgtune : https://github.com/osm2vectortiles/pgtune
> ( it is clean and simple code - for me )
> If no other better solution - I will try to customize ..

Good 👍  If it works similar/same to https://github.com/osm2vectortiles/osm2vectortiles/pull/171/files that would be perfect.

**Comment by stirringhalo** [comment]
@lukasmartinelli 

> Import takes 19hrs now with all the additional stuff we currently have. Quite increased since when we started.

19 hours? Is this for the import-external, import-osm, import-sql steps? I do know import-osm is slow once the actual OSM data has been dumped to DB. In non-diff mode, the writing of OSM without indexing took about half the time as diff mode!

> And import-sql with splitting and indizes takes another 0.5hr.

That's not too bad, and inline with what I was seeing.

Once my import catches up, probably by tomorrow, I will start my own export. If you focus on Delaware, Greenland and Chile, I will get the southern ontario region exported.

**Comment by lukasmartinelli** [comment]
Greenland export running since 21 hours without timeout (11hrs left)... good work @stirringhalo.
Once it is finished I need to examine it visually. Have you already checked how the tiles look @stirringhalo whether there are perhaps glitches due to subdividing ?

**Comment by stirringhalo** [comment]
@lukasmartinelli  
I didn't check just yet with a visual side-by-side comparison as I imagine many of the glitches would be due to styling and outlines (we won't be 100% compatible with Mapbox styles for oceans), but I did an ST_IsValid check for invalid features. I did see a few invalid features and dropped those on one of my tests. I don't remember the exact number but it wasn't a significant number. I will investigate how some of those invalid features are handled by the rendering.

There might be a small faint gap between subdivided features, perhaps from rounding issues internal to PostGIS. This is where an outline of 1 pixel might be necessary.

Looking at the buglist for ST_Subdivide, thankfully there hasn't been a rash of anything. Though we may have to be careful if we use ST_Subdivide in a more generic way on more tables like points: https://trac.osgeo.org/postgis/ticket/3522 . But I don't imagine there's a need to.

**Comment by lukasmartinelli** [comment]
> Greenland export running since 21 hours without timeout (11hrs left)... good work @stirringhalo.

No was the Delaware export. This export previously always failed but now it ran through in 1d and 7h and exported 588.9k tiles. Thanks @stirringhalo this PR really seems to help a lot.
This means we now recovered the most important part of missing data in #330.

So performance wise this PR is absolutely fine! 👍

**Comment by stirringhalo** [comment]
> No was the Delaware export. This export previously always failed but now it ran through in 1d and 7h and exported 588.9k tiles.

Awesome! Very thrilled to hear that. I should have a good chunk of my import completed Monday/Tuesday. Have you been able to do a visual inspection yet?

**Comment by lukasmartinelli** [comment]
> Awesome! Very thrilled to hear that. I should have a good chunk of my import completed Monday/Tuesday. Have you been able to do a visual inspection yet?

You can check it out here. (Just run `docker-compose up -d compare-visual`).
Looks good to me.

http://104.196.100.205/#13.97/42.3352/-83.0514

**Comment by stirringhalo** [comment]
@lukasmartinelli , question, any further timed out tiles or has this fix managed to remedy them all?

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli , question, any further timed out tiles or has this fix managed to remedy them all?

This was the uber fix. Changed some things however and made a new PR #367. Once this one is merged we can resolve this as well.

**Comment by stirringhalo** [comment]
> This was the uber fix. Changed some things however and made a new PR #367. Once this one is merged we can resolve this as well.

Extremely happy to hear that. My render stalled over the weekend (or so I thought) and despite restarting it Monday, did so again. I thought it was still a timeout issue on a bunch of large undivided features but I found it was due to the re-enabled RabbitMQ heartbeat in commit a62509. So my rendering continued to Mock-S3, but the jobs weren't being passed back to the "finished" queue. Solved that, hopefully mine will complete shortly too.

**Pull request merged**
