### PR TITLE
Refactor admin and water queries

### PR DESCRIPTION
**Pull request by manuelroth**
- Refactored the queries for layer admin and water

### CODE REVIEW

**Comment by manuelroth** [comment]
The mapping-qa doesn't work anymore for the layer water and admin, because the zoom level views are now mixed.

**Comment by lukasmartinelli** [comment]
> The mapping-qa doesn't work anymore for the layer water and admin, because the zoom level views are now mixed with natural earth and openstreetmap data. Not sure what to do. We can remove them from mapping-qa or reference the tables directly in the layer view.

Just checked out the **features/refactor-water-admin-query** branch. I get a mapping report and still 100% (even though there is osm_id 0..) - but had to drop the db.

**Comment by manuelroth** [comment]
This is because I reference the tables directly in the layer view. Otherwise it would not work.

Obviously this results in 100%
```sql
CREATE OR REPLACE VIEW water_layer AS (
    SELECT osm_id, timestamp, geometry FROM osm_water_polygon
    UNION
    SELECT osm_id, timestamp, geometry FROM osm_water_polygon_gen1
);
```
Following does not work, because there is data in the zoom level views which is not in the mapping (natural earth, water polygons)
```sql
CREATE OR REPLACE VIEW water_layer AS (
    SELECT osm_id, geometry FROM water_z0
    UNION ALL
    SELECT osm_id, geometry FROM water_z1
    UNION ALL
    SELECT osm_id, geometry FROM water_z2toz3
    UNION ALL
    SELECT osm_id, geometry FROM water_z4
    UNION ALL
    SELECT osm_id, geometry FROM water_z5toz7
    UNION ALL
    SELECT osm_id, geometry FROM water_z8toz12
    UNION ALL
    SELECT osm_id, geometry FROM water_z13toz14
);
```

**Comment by lukasmartinelli** [comment]
I somehow don't understand it sorry :grin: 
What is wrong with https://github.com/osm2vectortiles/osm2vectortiles/pull/268/commits/5d884891d6983144265aaac68def64d5cf0eaf67?

The qa report does match the osm ids of all the layers (aka the vector tile content) and what is mapped in imposm. Now we have **1 feature** too much in the layers - but this is correct. This is the unmapped osm id **0** which all external data has.

| tid                     | db_features | vt_features | percent | tables                                                                  | layers                                | 
|-------------------------|-------------|-------------|---------|-------------------------------------------------------------------------|---------------------------------------| 
| osm_admin_linestring    | 1716        | 1717        | 99.94   | {osm_admin_linestring}                                                  | {admin_layer}                         | 
| osm_aero_*              | 936         | 936         | 100.00  | {osm_aero_linestring,osm_aero_polygon}                                  | {aeroway_layer}                       | 
| osm_airport_*           | 81          | 81          | 100.00  | {osm_airport_point,osm_airport_polygon}                                 | {airport_label_layer}                 | 
| osm_barrier_*           | 44433       | 44433       | 100.00  | {osm_barrier_linestring,osm_barrier_polygon}                            | {barrier_line_layer}                  | 
| osm_building_*          | 1903832     | 1903832     | 100.00  | {osm_building_polygon_gen0,osm_building_polygon}                        | {building_layer}                      | 
| osm_housenumber_*       | 598921      | 598921      | 100.00  | {osm_housenumber_point,osm_housenumber_polygon}                         | {housenum_label_layer}                | 
| osm_landuse_*           | 218998      | 218998      | 100.00  | {osm_landuse_polygon,osm_landuse_polygon_gen0,osm_landuse_polygon_gen1} | {landuse_overlay_layer,landuse_layer} | 
| osm_mountain_peak_point | 3850        | 3850        | 100.00  | {osm_mountain_peak_point}                                               | {mountain_peak_label_layer}           | 
| osm_place_*             | 12382       | 12382       | 100.00  | {osm_place_geometry}                                                    | {place_label_layer}                   | 
| osm_poi_*               | 98304       | 98304       | 100.00  | {osm_poi_point,osm_poi_polygon}                                         | {poi_label_layer}                     | 
| osm_rail_station_point  | 2796        | 2796        | 100.00  | {osm_rail_station_point}                                                | {rail_station_label_layer}            | 
| osm_road_geometry       | 949125      | 949125      | 100.00  | {osm_road_geometry}                                                     | {road_layer,road_label_layer}         | 
| osm_water_linestring    | 54837       | 54837       | 100.00  | {osm_water_linestring}                                                  | {waterway_layer,waterway_label_layer} | 
| osm_water_polygon_*     | 24237       | 24238       | 100.00  | {osm_water_polygon_gen1,osm_water_polygon}                              | {water_layer,water_label_layer}       |

**Comment by manuelroth** [comment]
That's alright for me, just thought if the purpose of the mapping-qa is to compare the mapped features with features in vector tiles, the external data shouldn't be counted.

**Comment by manuelroth** [comment]
As you said the mapping-qa logic makes a `select count(distinct osm_id)` so the external data counts as 1.

**Comment by lukasmartinelli** [comment]
> That's alright for me, just thought if the purpose of the mapping-qa is to compare the mapped features with features in vector tiles, the external data shouldn't be counted.

Done with commit https://github.com/osm2vectortiles/osm2vectortiles/commit/25ed82707986bb65bd4d9c621151d0d8135922af. This way osm_id 0 aka external data is not counted.

**Pull request merged**
