### PR TITLE
Improved website design

### PR DESCRIPTION
**Pull request by klokan**
New version of osm2vectortiles.org with responsive CSS, clean url structure, improved texts.

Preview at: http://klokantech.github.io/osm2vectortiles/

### CODE REVIEW

**Comment by klokan** [comment]
@daliborjanak works on merging recent changes.

**Comment by daliborjanak** [comment]
PR could be merged now.

**Comment by lukasmartinelli** [comment]
Great work @daliborjanak!  Everything works smoothly and also works on the phone.

We will remove the osm2vectortiles-gh-pages.zip file and also configure Jekyll to support highlighted code sections.

**Comment by daliborjanak** [comment]
Thanks. I forget .zip file :( I'm using ```{% highlight html %}{% endhighlight %}``` for syntax highlighting. I will send you another PR with retina image support during day.

**Pull request merged**
