### PR TITLE
Testing Tilelive-copy timeouts

### PR DESCRIPTION
**Pull request by stirringhalo**
From #350 I have this sneaking suspicion that the timeouts isn't strictly a data issue but also a tilelive-copy issue.

If the data was too complex with too many vertices, you'd expect tilelive-copy to stall completely and process no tiles as it waits on Postgres to send back results. But it doesn't do that and tricks you by not showing you that it's still working.

By watching "slow" tiles (which can be forced to be all tiles by setting a low threshold), you can see that processing continues for all tiles. You can compare this to another region which doesn't normally timeout by modifying the BBOX in docker-compose.yml to be the other more inland region with the same dimensions.

If you grep the logs for slow tiles, you can see that nearly the same number of tiles are handled in the same amount of time. In-fact, if you raise the timeout threshold to allow the process to complete for the coastal region it will jump from ~2% to 100% after some time, exit cleanly and claim it successfully wrote to disk without actually doing so. Only the first 138 (~1-2%) tiles get written to MBTiles.

This behaviour happens whether the geometry is sub-divided or not. By the way, those tiles process significantly faster when subdivided. **Like 35ms per tiles instead of 5s!**

It's almost like there's an error that tilelive-copy should be throwing and is not displaying.

To demonstrate this, just do the regular postgis, import-external, import-osm, import-sql, export dance. This time, you will see all "slow" tiles show up in prompt and you can see that processing does proceed. Then, switch the bbox in docker-compose.yml and see the processing handle a similar number of tiles but complete properly.

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
> If you grep the logs for slow tiles, you can see that nearly the same number of tiles are handled in the same amount of time. In-fact, if you raise the timeout threshold to allow the process to complete for the coastal region it will jump from ~2% to 100% after some time, exit cleanly and claim it successfully wrote to disk without actually doing so. Only the first 138 (~1-2%) tiles get written to MBTiles.

Due to the reason with zero tiles mentioned in #350. Or at least I strongly suspect so.

**Comment by stirringhalo** [comment]
Makes sense, I think that also messed with the split_polygon benchmark as I expected those tasks to complete successfully!

Not sure at this point but the timeout may still need to be increased as with the default, it was timing out on the zero feature tiles even with the speedy st_subdivide. Not critical and easy to fix. I'll have a look into it.

**Comment by stirringhalo** [comment]
Yep, zero tiles still time it out as there's been no progress adding to mbtiles. Setting a slow timeout threshold, you can see if happen while tiles are still being processed as indicated by "slow".

**Comment by lukasmartinelli** [comment]
> Yep, zero tiles still time it out as there's been no progress adding to mbtiles. Setting a slow timeout threshold, you can see if happen while tiles are still being processed as indicated by "slow".

That makes sense, no tiles recorded - no progress recorded and then a failure is reported even though everything is fine. Thanks for clarifying. It is kind of a weird edge case in tilelive-copy.
In earlier version we used **tl copy** from https://github.com/mojodna/tl which deals differently (it does store empty tiles and does not time out but seems to be slower). Perhaps I will do a switch back for pyramid jobs.

> Suggest the timeout gets axed for now unless we still run into the issue again later. Or at least set it very high.

Let's set the timeout to something like 20 minutes.

**Comment by stirringhalo** [comment]
> That makes sense, no tiles recorded - no progress recorded and then a failure is reported even though everything is fine. Thanks for clarifying. It is kind of a weird edge case in tilelive-copy.
In earlier version we used tl copy from https://github.com/mojodna/tl which deals differently (it does store empty tiles and does not time out but seems to be slower). Perhaps I will do a switch back for pyramid jobs.

Don't really need to as the fix is so easy. Bumping up the timeout works well. I'll put together a PR with 20min timeouts. Do you think that will still work for Antarctica well as if it's 90% empty it will still timeout on large jobs?

**Pull request closed without merging**
