### PR TITLE
Refactoring imposm3 varname "osm_id" to "id" #304

### PR DESCRIPTION
**Pull request by ImreSamu**
see #304 

- [x] first version
- [x] update is working.   [see my test ] (https://gist.github.com/ImreSamu/8721d7ee7dcec02a62e3dc3e5e276af9)
- [x] more testing  ...

Status : work in progress.    Do not merge yet !!!!

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
I am running an import with the new mapping from this branch so we can then test this out globally.
Great work and very impressive QA with the tests - very glad to see it works with the diff updates.

**Comment by ImreSamu** [comment]
@lukasmartinelli  - I can't see, the Merge button ..

so please DO !     :)

**Comment by manuelroth** [comment]
@ImreSamu I think we forgot to give you write access. Can you see the merge button now?

**Comment by manuelroth** [comment]
@ImreSamu Oh, I have just a small non-technical improvement. We try to write all SQL upper-case to have a bit of consistency through the project. Would it be possible for you to make the `as` upper-case?

**Comment by ImreSamu** [comment]
*  Merge button OK :)
*  `as` upper-case :    Yes , but only tomorrow ..

( But no problem If you do this yourself   ...     )

**Comment by manuelroth** [comment]
Don't have permission to push on the branch of your fork of osm2vectortiles. You will have to do this. No problem if it happens tomorrow.

**Comment by ImreSamu** [comment]
@manuelroth 

>Don't have permission to push on the branch of your fork of osm2vectortiles.

Can you re-check again ?  I think -  it was because a `merge conflict` - and not a 'permission' problem.

I resolved the merge conflict & fixed travis error .
If the code looks good ( need a minimal code review ) -  you can merge.

**Comment by manuelroth** [comment]
> Can you re-check again ? I think - it was because a merge conflict - and not a 'permission' problem.

I resolved the merge conflict & fixed travis error .
If the code looks good ( need a minimal code review ) - you can merge.

Ok, I am fine with this you can merge.

**Comment by ImreSamu** [comment]
thanks. done!

**Pull request merged**
