### PR TITLE
Respect buffer in dirty tiles

### PR DESCRIPTION
**Pull request by lukasmartinelli**
Will test this on the world dataset whether it has performance impact.
Also need to verify whether it really works.
Resolves #232 #255

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
Okay ready to merge.

Would be glad if a second pair of eyes would look over the **tables.yml** @manuelroth.
You probably detect something immediately since you worked alot on the layers SQL.

https://github.com/osm2vectortiles/osm2vectortiles/blob/feature/respect-buffer-in-dirty-tiles/src/import-sql/tables.yml

**Comment by manuelroth** [comment]
- Found some cases where the buffer size was "not correct" for example layer landuse and landuse_overlay both use the table landuse_polygon, landuse has buffer size of 4 and landuse_overlay a buffer size of 8 =>  In this case we should go for 8 (same for layer water/water_label and waterway/waterway_label)
- Surprisingly the buffer size of layer poi_label was incorrect in our source project, corrected it from 128 to 64

**Comment by lukasmartinelli** [comment]
Ahh screwed up with pretty much all buffer values. Sorry.

> Surprisingly the buffer size of layer poi_label was incorrect in our source project, corrected it from 128 to 64

Oh yes see in Mapbox it is 64px.

**Comment by manuelroth** [comment]
No not your fault just found out in Streets v6 the buffer value for layer poi_label was indeed 128px

**Pull request merged**
