### PR TITLE
Replace LineStrings with Points

### PR DESCRIPTION
**Pull request by davidar**
Since mapbox has decided to claim ownership of the seas #387

### CODE REVIEW

**Comment by pnorman** [comment]
The linestrings in seas.geojson are different from MB Streets

**Comment by pnorman** [comment]
Repeating an an analysis from https://github.com/osm2vectortiles/osm2vectortiles/issues/387#issuecomment-238060253...

seas.geojson was introduced in 3b1b4f9 by @lukasmartinelli and may be based on an earlier marine.sql file in 6531e88. The contents of this file appear to be OSM-derived, and there [used to be code](https://github.com/osm2vectortiles/osm2vectortiles/commit/2c08b6d4aaee542989b70f57ef3f7f1360f2ff9f#diff-de2ee30f49dce057f96d01693fce4e8f) which used OSM data for marine labels.

**Comment by pnorman** [comment]
seas.geojson being osm-derived and ODbL, its license needs to be stated somewhere. I recommend putting a file in src/import-external stating the license and source of all the files there.

**Comment by lukasmartinelli** [comment]
> seas.geojson was introduced in 3b1b4f9 by @lukasmartinelli and may be based on an earlier marine.sql file in 6531e88. The contents of this file appear to be OSM-derived, and there used to be code which used OSM data for marine labels.

Regarding the claim of #387. This is how it was done.

1. Overpass query

```
[out:json][timeout:25];
// gather results
(
  node["place"="ocean"]({{bbox}});
  node["place"="sea"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

2. Export GeoJSON
3. And then I sat down **3-4 hours and drew lines for the marine labels myself!!**. That was really boring manual labor I did there just to have good marine lines without copying anything.
4. I even hunted for some translations in Wikipedia for some of the seas/lakes

> seas.geojson being osm-derived and ODbL, its license needs to be stated somewhere. I recommend putting a file in src/import-external stating the license and source of all the files there.

Don't you think that is already covered within *Data Downloads*? In the README

> The project is under the MIT license while the data downloads use the Open Database License from OpenStreetMap.

**Comment by pnorman** [comment]
> Don't you think that is already covered within Data Downloads? In the README
> 
>> The project is under the MIT license while the data downloads use the Open Database License from OpenStreetMap.

Legally? Maybe. It's not clear that a file in the repo is a data download. If all the stuff in import-external is a data download, the text is wrong since Natural Earth is used.

The reason I'd like to see it stated there is it is

1. Makes it clear what is from where
2. Documents the source and how the files were created

That seas.geojson is OpenStreetMap ocean and sea nodes with hand-drawn lines for some labels is useful information if you ever want to modify the file or track down a bug.

**Comment by davidar** [comment]
FWIW, I don't mind if this PR is closed, but I agree with @pnorman that it would probably be helpful to be more explicit about data provenance given that mapbox has decided to start spreading legal FUD.

**Pull request closed without merging**
