### PR TITLE
Getting Started tutorial created

### PR DESCRIPTION
**Pull request by manuelroth**
- Removed links to tutorials on documentation page as discussed in #291 
- Created a getting started tutorial including serving vector tiles([simple node server](https://github.com/osm2vectortiles/mbtiles-server-example)), display map in browser and alternatively using the public CDN
- Updated all links to include target=_blank (new tab opens)

@lukasmartinelli would love to know if the getting started tutorial is now simple enough and if you see further improvements

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
Our goal is to have this time a tutorial without using Docker since that confused many new users not familiar with it. And this PR is a good step in this direction. Forgive the minor complaints.

Would be really cool if users can just `npm install <tileserver>` and then do something like `tileserver afghanistan.mbtiles` and that's it. No cloning a repo or something. Also while it is really cool to see how easy it is to serve MBTiles this doesn't deal with all the edge cases like requests that are out of bounds or filter zoom levels or PBFs that are not gzipped.

Something like tessera (tessera is not really intuitive however because you see a blank page when serving PBFs). We can merge it and discuss it further on friday or wait until then.

I would like to use `tileserver-gl` but it could not npm install it due to build errors since (and for just serving PBFs we don't necessarily need mapbox-gl as dependency). And the `config.json` also makes it a bit complicated for new users again.

The rest I think is pretty solid (some style things but we can fix that later).

Also if we say

> We have prepared a repository containing all the necessary files for you. Simply clone this repository, run npm install, download your desired extract and run node index.js and the vector tiles are getting served.

We should probably list the code for the lazy user not as text.

```sh
git clone https://github.comosm2vectortiles/...
npm install
wget https://osm2vectortiles/downloads/zurich.mbtiles
node index.js
```

Same here I guess.

> To get you started quickly we have created a repository with the necessary files and assets. Clone this repository, start your favorite webserver(`npm install http-server -g) and you should see the map in your browser.




- [ ] Perhaps adapt the main page with the new links or change the texts?

free_vector_tiles_from_openstreetmap_ _osm2vectortiles_

- [ ] The stylesheet screws up code formatting

getting_started_ _osm2vectortiles_

**Comment by manuelroth** [comment]
Thanks for your suggestions, updated main page, fixed wired code formatting and replace instructions with code instructions.

> Would be really cool if users can just npm install <tileserver> and then do something like tileserver afghanistan.mbtiles and that's it. No cloning a repo or something. Also while it is really cool to see how easy it is to serve MBTiles this doesn't deal with all the edge cases like requests that are out of bounds or filter zoom levels or PBFs that are not gzipped.

Yes, this should be very easy. I like that in this example people can actually understand what happens and that there is no magic behind serving vector tiles. But it would be much easier to just do something like npm install <tileserver> && tileserver zurich.mbtiles. Maybe we can have an easy example in the tutorial and additionally say something like "we have packaged this into an npm module just run npm install tileserver". Let's further discuss this tomorrow.

**Comment by manuelroth** [comment]
I'm glad you like it 😄  Added some nice icons, updated the description and fixed the bug where the placeholder text was oddly misaligned in Safari. 

downloads_ _osm2vectortiles

**Comment by hannesj** [comment]
> Something like tessera (tessera is not really intuitive however because you see a blank page when serving PBFs). We can merge it and discuss it further on friday or wait until then.

It should show a visualization of the vector tiles as long as you have tilelive-xray and all of its peer dependencies installed along with mbtiles.

**Comment by hyperknot** [comment]
This approach would limit you to setups which doesn't need mapnik in any of the dependencies, as compiling mapnik is seriously voodoo and it's only been offered in binary form on a very limited set of OS-es (like Ubuntu 14.04 + node 0.10). Pretty much a random user has no chance of being on a system for which mapnik is binary supplied via npm.

**Comment by lukasmartinelli** [comment]
Discussed approach now.

## Maps 
On the maps section on the homepage we want to show all Mapbox GL styles (modified to not needing Mapbox terrain and pointing to the vector tile CDN).
And like the Mapbox GL examples page we want to provide the HTML code to embedd so you can copy and play with it. This is that the users can get started as quickly as possible.
In the tutorial we then to deeper and explain how to host the tiles yourself.

cursor_and_collection_of_map_ _osm2vectortiles

cursor_and_a_simple_map___mapbox

## Getting Started Tutorial

### Part 1

First show the example with the CDN.
Tell the user to go to Maps choose an example, create a index.html page and use it there.
Baam first success story.

### Part 2

Then we show the second part that if you don't want to use a CDN how to serve your own tiles.

There we create a very simple MBTiles PBF serving tileserver based on what Manuel started (with no deps on MapboxGL or Mapnik) package the styles and fonts into it and publish it to npm.
And @hyperknot is absolutely right there, it is important that this runs everywhere without compiling stuff  with node-gyp if possible. 

Then when you start the tileserver with something like `tileserver afghanistan.mbtiles`.
We display the same map section as on osm2vectortile including the copy example but there we replace the `source` in the styles with the url pointing to the local tileserver URL.

This tileserver is not meant for production but to get you serving your own tiles fast.
After that we recommend switching to something like tileserver-gl, tessera or the other many options (like putting the PBFs on S3).

**Comment by lukasmartinelli** [comment]
We once discussed putting the filesize into the CSV file as well.
But while adding the filesize to the CSV is doable maintaining later will be kind of a chore.
We then need to update the CSV weekly with the newest filesizes.

Can we just leave out the filesize for city and country extracts?

**Comment by manuelroth** [comment]
> We once discussed putting the filesize into the CSV file as well.
But while adding the filesize to the CSV is doable maintaining later will be kind of a chore.
We then need to update the CSV weekly with the newest filesizes.

> Can we just leave out the filesize for city and country extracts?

I agree, maintaining this would be a pain. Found out that it is pretty easy to get the metadata of a bucket. One can just make a [GET request](https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/?prefix=v1.0/extracts/) on the bucket and it will return metadata about all of its objects. Just pushed a commit which retrieves the file size for each object of this metadata. 
This way we don't have to maintain the size value, the draw back is that we need to do an extra ajax call. But I think it's worth it, it is an important information to decide whether you want to download it or not.

**Comment by lukasmartinelli** [comment]
Of course since the bucket is public you can do that.
Good idea and initiative, thanks.

This way it is decoupled from the CSV which is perfect.

**Pull request merged**
