### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by vitaly-t**
Refactoring the use of pg-promise:
* executing multiple requests as a batch within a task context;
* setting `q` as the promise library for pg-promise.

### CODE REVIEW

**Comment by manuelroth** [comment]
Thank you very much for your contribution. Executing the queries as a batch is definitely more efficient. I saw that you are actually the maintainer of the pg-promise module. How did you find our repository?- I think this is a very interesting way of showing the users of your library how they can improve their code.

**Comment by vitaly-t** [comment]
GitHub search engine can show you the most recent uses of your library ;)

**Comment by manuelroth** [comment]
That's awesome, thank you for taking the time. I will definitely merge your contribution.

**Comment by vitaly-t** [comment]
The code could be improved further, by replacing this code:
```js
 return result.max;
                })
                .then(function (timestamp) {
```
with this one:
```js
var timestamp = result.max;
```
i..e there is no need for an extra `.then` there ;)

**Comment by manuelroth** [comment]
Thanks for your suggestion, was a bit too fast with the merging;) Pushed it to the master branch

**Comment by vitaly-t** [comment]
Throwing another one back at ya ;) 
https://github.com/osm2vectortiles/osm2vectortiles/pull/143

**Comment by vitaly-t** [comment]
@manuelroth I can see you reversed most of the changes there, and for the worse, because now it again tries to allocate a virtual connection for every single request, instead of doing once, inside a task.

**Comment by lukasmartinelli** [comment]
> @manuelroth I can see you reversed most of the changes there, and for the worse, because now it again tries to allocate a virtual connection for every single request, instead of doing it once, inside a task.

No worries we are fully aware of that - we just had to port over an old piece of code in a rush to see whether it is faster. We were planning refactor the code again to use the Task feature.

**Pull request merged**
