### PR TITLE
Automate Extracts

### LINKED ISSUE #113: MBTiles Metadata (Center) incorrect
When uploading an MBTiles file from http://osm2vectortiles.org/ to Mapbox Studio, I get "Center lon value must be between bounds [east/west lon value corresponding to that region]". 

Could be a Mapbox Studio error but my guess is, it's a problem in the files. (Sorry, if not!)

Tried Switzerland, Croatia, Portugal and Zurich.

screen shot 2016-01-12 at 15 22 24

screen shot 2016-01-12 at 15 14 50

### PR DESCRIPTION
**Pull request by lukasmartinelli**
The script creates all country extracts and sets the metadata accordingly. It will create the extracts serially (not in parallel). Had a paralell version once but it happened alot that tilelive took too much memory on a system.

This should resolve #113, #124, #103.
Need to test it first (by following the documentation with sample extracts) before we can merge it.

### CODE REVIEW

**Comment by muesliq** [comment]
Horray!

**Comment by manuelroth** [comment]
Looks good to me. Do you want to add the city extracts in a later pull request?

**Comment by manuelroth** [comment]
We could probably add the functionality to merging lower zoom levels (planet z0 to z5) into the extracts in a later pull request

**Comment by lukasmartinelli** [comment]
You're right, we stil lneed to add:
- [ ] Merging z0 to z5 into the extracts
- [ ] Add city boundaries

Hm, let's keep this PR open until it's done. It is pretty standalone so merging shouldn't be an issue.

**Comment by manuelroth** [comment]
Oke, I agree. Let's discuss it further on thursday.

**Comment by lukasmartinelli** [comment]
City boundaries are in separate ticket #146 
Also added automated S3 upload so now we can just kickstart the extracts and it will
upload new versions once we have a new **updated** planet file.
This also resolves #145

**Pull request merged**
