### PR TITLE
use_single_id_space in imposm mapping

### LINKED ISSUE #281: imposm3 mapping update research.   conclusion ->  use_single_id_space: true
I made some test with imposm3 diff update and with the current [osm2vectortiles mapping.yml] (https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-osm/mapping.yml )
My suggestion:   **use_single_id_space: true **

The problem :   this is dangerous combination:
* `type_mappings` + multiple osm type
* with `imposm3 diff`
* with `use_single_id_space: false`

My test method :
* theoretical input data - see full test code [y.sh](https://gist.github.com/ImreSamu/9cbad28eb0a211105934b3718a25fda6#file-y-sh)
* 3 nodes, 3 ways ,3 relations -> testing   osm_id collision  with mapping.yml
* modified only one object  -  key: `name`+ `-UPDATED!!!!!`
 * and checked the update mechanism.
  * with  `use_single_id_space: false`
  * with  `use_single_id_space: true`

Result:
* without : use_single_id_space: true  -> some data loss.

Why:
*   nodes and ways  can be a same  `osm_id`  and when one of is updated, both of them is deleted, but only the updated inserted again.
 *   select  osm_id=2  
   *  2 | hamlet | n2-place-hamlet ( osm_id =2 and NODE )
    * 2 | islet      | w2-place-islet-inner ( osm_id=2 and  WAY )

see more: 
* http://gis.stackexchange.com/questions/103572/are-osm-ids-unique-over-all-object-types/103585

### use_single_id_space: false  -  current  settings
https://gist.github.com/ImreSamu/9cbad28eb0a211105934b3718a25fda6#file-single_id_false_test_report-md
in the worst case  -  data lost - see    r3-place-archipelago 

```sql
 osm_id |       type        | place_geometry_name____before_diff_mod_r3 
--------+-------------------+-------------------------------------------
     -3 | archipelago       | r3-place-archipelago
     -2 | island            | r2-place-island
     -1 | residential       | r1-landuse-residential
      1 | neighbourhood     | n1-place-neighbourhood
      2 | hamlet            | n2-place-hamlet
      2 | islet             | w2-place-islet-inner
      3 | isolated_dwelling | n3-place-isolated_dwelling
      3 | aboriginal_lands  | w3-boundary-aboriginal_lands-inner
(8 rows)

 osm_id |       type       | place_geometry_name____after_diff_mod_r3 
--------+------------------+------------------------------------------
     -3 | archipelago      | r3-place-archipelago-UPDATED!!!!!
     -2 | island           | r2-place-island
     -1 | residential      | r1-landuse-residential
      2 | islet            | w2-place-islet-inner
      2 | hamlet           | n2-place-hamlet
      3 | aboriginal_lands | w3-boundary-aboriginal_lands-inner
(6 rows)
```
expecting : same record as before  , now  only 6  ( instead of 8 )
missing:
* n1-place-neighbourhood
* n3-place-isolated_dwelling
 

### use_single_id_space: true
https://gist.github.com/ImreSamu/9cbad28eb0a211105934b3718a25fda6#file-single_id_true_test_report-md

this is so much better!
`r3-place-archipelago-UPDATED!!!!!` - ok   and no other osm_id -s destroyed.

```sql
       osm_id        |       type        | place_geometry_name____before_diff_mod_r3 
---------------------+-------------------+-------------------------------------------
 -100000000000000003 | archipelago       | r3-place-archipelago
 -100000000000000002 | island            | r2-place-island
 -100000000000000001 | residential       | r1-landuse-residential
                  -3 | aboriginal_lands  | w3-boundary-aboriginal_lands-inner
                  -2 | islet             | w2-place-islet-inner
                   1 | neighbourhood     | n1-place-neighbourhood
                   2 | hamlet            | n2-place-hamlet
                   3 | isolated_dwelling | n3-place-isolated_dwelling
(8 rows)

       osm_id        |       type        | place_geometry_name____after_diff_mod_r3 
---------------------+-------------------+------------------------------------------
 -100000000000000003 | archipelago       | r3-place-archipelago-UPDATED!!!!!
 -100000000000000002 | island            | r2-place-island
 -100000000000000001 | residential       | r1-landuse-residential
                  -3 | aboriginal_lands  | w3-boundary-aboriginal_lands-inner
                  -2 | islet             | w2-place-islet-inner
                   1 | neighbourhood     | n1-place-neighbourhood
                   2 | hamlet            | n2-place-hamlet
                   3 | isolated_dwelling | n3-place-isolated_dwelling
(8 rows)
```

_if you need my test code: ask - and I create a pull request._

### PR DESCRIPTION
**Pull request by lukasmartinelli**
Resolves #281 

Only possible thanks to the research of @ImreSamu in #281.

*This is how I understand it, please correct me @ImreSamu *
`use_single_id_space=true` will divides the id range up into three ranges.

`id < - 1e17`: Ways
`0 < id > - 1e17 `: Relations
`id > 0`: Points

What I can do now is to map the relations back into the negative range (by adding `1e17`).
And ways back to the positive range (by making them absolute). And then the functions we created previously (`osm_id_linestring`, `osm_id_polygon`, `osm_id_point`, `osm_id_geometry` handle the rest because they make the decision based on geometry type and whether it originated from a relation.

drawing

### CODE REVIEW

**Comment by ImreSamu** [comment]
just 1 quick comment:
* your graph is correct, 

but here  need reverse  ways <-> Relations :   
```
id < - 1e17: Ways
0 < id > - 1e17: Relations
```

imho - the correct :
```
id < - 1e17: Relations 
0 < id > - 1e17: Ways
```

see my examples - from the test data #281 

### realtions
```sql
 -100000000000000003 | archipelago       | r3-place-archipelago-UPDATED!!!!!
 -100000000000000002 | island            | r2-place-island
 -100000000000000001 | residential       | r1-landuse-residential
 ```

### ways
```sql
                  -3 | aboriginal_lands  | w3-boundary-aboriginal_lands-inner
                  -2 | islet             | w2-place-islet-inner
```                  

### nodes
```sql                  
                   1 | neighbourhood     | n1-place-neighbourhood
                   2 | hamlet            | n2-place-hamlet
                   3 | isolated_dwelling | n3-place-isolated_dwelling
```

**Comment by lukasmartinelli** [comment]
> imho - the correct :

Ups switched ways and relations in the written example.
Thanks for the review and detailed example.

So what the code now does is for relation it takes the relation and get's back the real OSM id (but still negated if it is a relation.
And then our osm_id functions that already exist decide what the Mapbox OSM Id will be.

**Relation**

` -10000000000000003 + 1e17 = -3`

If it is a polygon for example the `osm_id_polygon` function will now do

`(abs(-3) * 10) + 4 = 34`

If it would not have been negative it means it is a polygon was not made out of a relation
and the osm id looks like this.

`(3 * 10) + 2 = 32`

**Comment by ImreSamu** [comment]
as usual ..  it is a matter of taste .. 

but 
* with the #284  patch there will be a problem, because we will lost the geometry information (` osm_id_geometry()` )   [ this is polygon or not ? ]   
  so there will be a problem with the proposed  2 step conversion , without redesign.


  
my alternative solutions:
```sql

-- specification : https://www.mapbox.com/vector-tiles/mapbox-streets-v7/
-- osm_ids :  imposm3 single space id
CREATE OR REPLACE FUNCTION osm_ids2mbid (osm_ids BIGINT, is_polygon bool ) RETURNS BIGINT AS $$
BEGIN
 RETURN CASE
   WHEN                      (osm_ids >=    0  )                    THEN (       osm_ids          * 10)       -- +0 point 
   WHEN (NOT is_polygon) AND (osm_ids >= -1e17 ) AND (osm_ids < 0 ) THEN ( (abs( osm_ids)       ) * 10) + 1   -- +1 way linestring
   WHEN (    is_polygon) AND (osm_ids >= -1e17 ) AND (osm_ids < 0 ) THEN ( (abs( osm_ids)       ) * 10) + 2   -- +2 way poly
   WHEN (NOT is_polygon) AND (osm_ids <  -1e17 )                    THEN ( (abs( osm_ids) -1e17 ) * 10) + 3   -- +3 relations linestring
   WHEN (    is_polygon) AND (osm_ids <  -1e17 )                    THEN ( (abs( osm_ids) -1e17 ) * 10) + 4   -- +3 relations poly                     
   ELSE 0
 END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


CREATE OR REPLACE FUNCTION is_polygon( geom geometry) RETURNS bool AS $$
BEGIN RETURN CASE
        WHEN ST_GeometryType(geom) IN ('ST_Polygon', 'ST_MultiPolygon') THEN true
        ELSE false
      END;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


select osm_id
      ,osm_ids2mbid ( osm_id,   is_polygon( geometry ) )  as from_real_geom
      ,osm_ids2mbid ( osm_id,   false                  )  as from_fake_geom_false 
      ,osm_ids2mbid ( osm_id,   true                   )  as from_fake_geom_true       
from osm_place_geometry ;

       osm_id        | from_real_geom | from_fake_geom_false | from_fake_geom_true 
---------------------+----------------+----------------------+---------------------
 -100000000000000003 |             34 |                   33 |                  34
 -100000000000000002 |             24 |                   23 |                  24
 -100000000000000001 |             14 |                   13 |                  14
                   1 |             10 |                   10 |                  10
                  -3 |             32 |                   31 |                  32
                  -2 |             22 |                   21 |                  22
                   2 |             20 |                   20 |                  20
                   3 |             30 |                   30 |                  30
(8 rows)


```

 
and carefully - we can use the  `is_polygon` parameter for tables - without checking real geometry. 

now
```sql
 SELECT osm_id_geometry(osm_id, geometry) as osm_id
             , geometry
              , barrier_line_class(type) AS class
          FROM barrier_line_z14
```

But if we knows that `barrier_line_z14`  is not contains polygons,
then we can use the 'false' constant - to the 'is_polygon' information.
[  and  we can add a Check Constraints for safer implementation ]

so the optimal will be:
```sql
 SELECT osm_ids2mbid ( osm_id,   false  )  as osm_id
             , geometry
              , barrier_line_class(type) AS class
          FROM barrier_line_z14
```

This is not perfect yet ,   but  maybe you can reuse some ideas ..

**Comment by ImreSamu** [comment]
whatever you choose  please double check the  `id: place_label`  - `osm_id` conversion,  
* because everything will be a node. (  after this change:  #284  )

https://github.com/osm2vectortiles/osm2vectortiles/blob/436c1b028276a7fc5edff2519be871bcd6108582/osm2vectortiles.tm2source/data.yml#L645

**Comment by lukasmartinelli** [comment]
> my alternative solutions:

That's my dream scenario - having a `osm_ids2mbid` function.
Can you push the `osm_ids2mbid` function to this branch?
I gave you contributor access on osm2vectortiles as we really appreciate your input and work.

> with the #284 patch there will be a problem, because we will lost the geometry information (osm_id_geometry() ) [ this is polygon or not ? ]

Yes what happens there is that the Mapbox osm_id will be wrong for place points from polygons.
Was already thinking about creating another table in the mapping so we can keep the information
but with the `osm_ids2mbid` the problem can be solved easily because there are only points and polygons in the table we can call `osm_ids2mbid(osm_id, true)` and it will choose the correct one.

**Comment by ImreSamu** [comment]
added the functions : https://github.com/osm2vectortiles/osm2vectortiles/pull/290

>We gave you contributor access on osm2vectortiles as we really appreciate your input and work.

Thank you! :)

**Comment by lukasmartinelli** [comment]
With `osm_ids2mbid` it has gotten much easier.
Transformed the tm2source project.

1. Where we used `osm_id_point` we now use `osm_ids2mbid(geom, true)` since we only make points out of polygons
2. Where we used `osm_id_linestring` we now use `osm_ids2mbid(geom, false)`
3. Where we used `osm_id_polygon` we now use `osm_ids2mbid(geom, true)`
4. Where we used `osm_id_geometry` and the possible geometries where only point and polygons we now use `osm_ids2mbid(geom, true)`
5. Where we used `osm_id_geometry` and the possible geometries where ways and polygons (`road`, `barrier_line`) we now use `osm_ids2mbid(geom, is_polygon(geom))`

**Pull request merged**
